//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by bionicspider.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_BIONICSPIDER_DIALOG         102
#define IDS_APP_NAME                    102
#define IDS_WARNING_REMOVE_WINDOW       103
#define IDS_WARNING_REMOVE_GROUP        104
#define IDS_WARNING_REMOVE_ALL_GROUPS   105
#define IDS_WARNING_GROUP_NOT_SELECTED  106
#define IDS_WARNING_SINGLE_GROUP        107
#define IDS_GROUP_NEW                   108
#define IDS_ROOT_NEW                    109
#define IDS_WINDOW_RENAME               110
#define IDS_ROOT_DEFAULT_NAME           111
#define IDS_GROUP_DEFAULT_NAME          112
#define IDS_INFO_SELECTION_ROOT         113
#define IDS_HOTKEY_FILE                 114
#define IDS_HOTKEY_DEFAULT_GROUPS       114
#define IDS_WARNING_CLOSE_WINDOW        115
#define IDS_HOTKEY_LIST                 116
#define IDS_INVALID_HOTKEY              117
#define IDS_REGISTRY_PATH               118
#define IDS_HOTKEY_REGKEY               119
#define IDS_HOTKEY_REGKEY_MISC          119
#define IDS_HOTKEY_DEFAULTS             120
#define IDS_HOTKEY_DEFAULT_MISC         120
#define IDS_DEFAULT_GROUP               121
#define IDS_GROUPS_REGKEY               122
#define IDS_MENU_DEFAUTS                123
#define IDS_MENU_REGKEY                 124
#define IDS_EXIT_WARNING                125
#define IDS_SEEKER_WARNING              126
#define IDS_HOTKEY_DEFAULT_WARNING      127
#define IDR_MAINFRAME                   128
#define IDS_SET_HOTKEY_WARNING          128
#define IDS_HOTKEY_WARNING              128
#define IDR_MENU                        129
#define IDS_WEB_URL                     129
#define IDR_ACCEL                       130
#define IDS_EMAIL                       130
#define IDS_UPDATE_SCRIPT_URL           131
#define IDS_INFO                        132
#define IDS_WINMEMORY                   133
#define IDS_INFO_SELECTION_GROUP        134
#define IDD_EDITDLG                     135
#define IDS_GROUPMEMORY                 135
#define IDB_BITMAP_WEBSEEKER            136
#define IDS_ADDWINCAP                   136
#define IDC_CURSOR_WEBSEEKER            137
#define IDS_ADDWINCAP_DEFAULT           137
#define IDB_BITMAP_EMPTYWEBSEEKER       138
#define IDS_ADDWINCAP_ERROR             138
#define IDS_HOTKEY_REMOVE               139
#define IDS_HOTKEY_REMOVE_ALL           140
#define IDI_ICON_FOLDER                 141
#define IDS_TOOLTIP_SEEKER              141
#define IDS_TOOLTIP_HOTKEY_EDIT         142
#define IDD_DIALOG_HOTKEYS              143
#define IDS_TOOLTIP_HOTKEY_SET          143
#define IDB_BITMAP_1x1_HORT             144
#define IDS_TOOLTIP_HOTKEY_REMOVE       144
#define IDB_BITMAP_1x1_VERT             145
#define IDS_TOOLTIP_HOTKEY_DEFAULT      145
#define IDB_BITMAP_2x2                  146
#define IDS_TOOLTIP_HOTKEY_REMOVE_ALL   146
#define IDS_APP_TITLEBAR                147
#define IDS_APP_TITLEBAR_DOCKED         148
#define IDI_ICON_FOLDER_OPEN            149
#define IDS_UPDATECHECK_TRUE            149
#define IDI_ICON_ROOT                   150
#define IDS_UPDATECHECK_FALSE           150
#define IDI_ICON_ROOT_OPEN              151
#define IDS_UPDATECHECK_NONET           151
#define IDS_INFO_WINDOW                 152
#define IDS_YES                         153
#define IDS_NO                          154
#define IDS_DELIMINATOR                 155
#define IDB_ABOUT                       156
#define IDS_MENU_CHECKED                156
#define IDS_MENU_UNCHECKED              157
#define IDS_BIONICSPIDER_VER            158
#define IDS_WARNING_CLOSE_GROUP         159
#define IDS_WARNING_REMOVE_WINGROUP     160
#define IDS_WARNING_ROOT_CLOSE          161
#define IDS_WARNING_ROOT_REMOVE         162
#define IDS_HOTKEYDLG_ENABLE            163
#define IDS_HOTKEYDLG_REMOVE            164
#define IDS_TOOLTIP_HOTKEY_TABS         165
#define IDS_HOTKEY_REGKEY_GROUPS        166
#define IDS_FONT_DEFAULT                167
#define IDS_FONT_REGKEY                 168
#define IDD_UPDATE_CHECK                168
#define IDS_FONT_COLOR_REGKEY           169
#define IDD_UPGRADE                     169
#define IDD_UPGRADE_MSG                 169
#define IDS_HELP_PATH                   170
#define IDS_TRIAL_DAYS_LEFT             171
#define IDS_TRIAL_UNREGISTRED           172
#define IDS_TRIAL_KEY_INSTALLED         173
#define IDS_TRIAL_KEY_INVALID           174
#define IDS_WEB_URL_UPDATE              175
#define IDS_UPDATECHECK_CHECKING        176
#define IDS_BIONICSPIDER_VERSION_NUM    177
#define IDS_STRING178                   178
#define IDS_UPGRADE                     178
#define IDC_BIONICTREE                  1000
#define IDC_EDIT_INPUT                  1001
#define IDC_STATIC_EDIT_TEXT            1002
#define IDC_STATIC_SELECTION_INFO       1005
#define IDC_WEBSEEKER                   1006
#define IDC_STATIC_INFO                 1007
#define IDC_STATIC_LEFT                 1008
#define IDC_STATIC_RIGHT                1009
#define IDC_WINDOW_ICON                 1010
#define IDC_DATA_ICON                   1010
#define IDC_LIST_HOTKEYS                1011
#define IDC_BUTTON_HOTKEY               1012
#define IDC_BUTTON_HOTKEY_DEFAULT       1013
#define IDC_CHECK_HOTKEYS               1014
#define IDC_WEB_ADDRESS                 1015
#define IDC_EMAIL                       1016
#define IDC_BS_ICON                     1017
#define IDC_BS_TITLE                    1018
#define IDC_COPYRIGHT                   1019
#define IDC_ABOUT                       1021
#define IDC_STATIC_OK                   1022
#define IDC_STATIC_FRAME                1023
#define IDC_STATIC_FRAME_REG            1024
#define IDC_AUTHOR                      1025
#define IDC_TAB_HOTKEY_TYPE             1026
#define IDC_BUTTON_HOTKEY_TOGGLE        1027
#define IDC_BUTTON_HOTKEY_REMOVE_ALL    1028
#define IDC_EDIT_USERNAME               1030
#define IDC_EDIT_KEY                    1031
#define IDC_USER                        1032
#define IDC_EXPIRE                      1033
#define IDC_UPDATE_MSG                  1034
#define IDC_UPDATE_ADDRESS              1035
#define IDC_LIST_GROUPS                 1036
#define IDC_UPGRADE_URL                 1037
#define IDC_UPGRADE_TEXT                1038
#define ID_ROOT_GROUP                   32772
#define ID_ROOT_ADDGROUP                32773
#define ID_ROOT_HIDEALLGROUPS           32774
#define ID_ROOT_SHOWALLGROUPS           32775
#define ID_ROOT_MAXIMIZEALLGROUPS       32776
#define ID_ROOT_MINIMIZEALLGROUPS       32777
#define ID_ROOT_RESTOREALLGROUPS        32778
#define ID_ROOT_SORTALLGROUPS           32779
#define ID_ROOT_CLOSEALLGROUPS          32780
#define ID_ROOT_REMOVEWINDOWSINALLGROUPS 32781
#define ID_ROOT_REMOVEALLGROUPS         32782
#define ID_ROOT_RENAMEROOT              32783
#define ID_GROUP_HIDEALLWINDOWS         32784
#define ID_GROUP_SHOWALLWINDOWS         32785
#define ID_GROUP_MAXIMIZEALLWINDOWS     32786
#define ID_GROUP_MINIMIZEALLWINDOWS     32787
#define ID_GROUP_RESTOREALLWINDOWS      32788
#define ID_GROUP_TILEWINDOWS            32789
#define ID_TILEWINDOWS_1X1HORT          32790
#define ID_TILEWINDOWS_1X1VERT          32791
#define ID_TILEWINDOWS_2X2              32792
#define ID_GROUP_GROUPPOSITIONS         32793
#define ID_GROUPPOSITIONS_GROUPMEMORY   32794
#define ID_GROUPPOSITIONS_RECALLALL     32795
#define ID_GROUP_ADDWINDOWBYTITLE       32796
#define ID_GROUP_SORTALLWINDOWSINGROUP  32797
#define ID_GROUP_CLOSEALLWINDOWSINGROUP 32798
#define ID_GROUP_REMOVEALLWINDOWSINGROUP 32799
#define ID_GROUP_REMOVETHISGROUP        32800
#define ID_GROUP_RENAMETHISGROUP        32801
#define ID_WINDOW_HIDEWINDOW            32802
#define ID_WINDOW_SHOWWINDOW            32803
#define ID_WINDOW_FOREGROUNDWINDOW      32804
#define ID_WINDOW_MAXIMIZE              32805
#define ID_WINDOW_MINIMIZE              32806
#define ID_WINDOW_RESTORE               32807
#define ID_WINDOW_ALWAYSONTOP           32808
#define ID_WINDOW_CLOSE                 32809
#define ID_WINDOW_EXPLORER              32810
#define ID_EXPLORER_CONSOLE             32811
#define ID_EXPLORER_CLONE               32812
#define ID_WINDOW_RENAME                32813
#define ID_WINDOW_REMOVE                32814
#define ID_HELP_CONTENTS                32815
#define ID_HELP_ABOUT                   32816
#define ID_BIONICSPIDER_EXIT            32821
#define ID_DOCKING_ENABLEDOCKING        32822
#define ID_DOCKING_RIGHT                32823
#define ID_DOCKING_LEFT                 32824
#define ID_BIONICSPIDER_ALWAYSONTOP     32825
#define ID_BIONICSPIDER_WARNINGS        32826
#define ID_BIONICSPIDER_SWITCHGROUP     32827
#define ID_BIONICSPIDER_SWITCHWINDOWS   32828
#define ID_BIONICSPIDER_TRAYPOPUP       32829
#define ID_WINDOW_MINIMIZETOTRAY        32830
#define ID_BIONICSPIDER_COMPACT         32831
#define ID_BIONICSPIDER_HOTKEYS         32832
#define ID_Menu                         32833
#define ID_BIONICSPIDER_AUTOGROUP       32834
#define ID_HELP_CHECKFORUPDATE          32835
#define ID_Menu32836                    32836
#define ID_POSITIONING_RECALL           32837
#define ID_WINDOW_POSITIONING           32838
#define ID_POSITIONING_MEMORY           32839
#define ID_POSITIONING_RECALL32840      32840
#define ID_BIONICSPIDER_SWITCHCURSOR    32842
#define ID_HELP_ENTERKEY                32843
#define ID_Menu32844                    32844
#define ID_BIONICSPIDER_HIDE            32845
#define ID_BIONICSPIDER_FONTS           32868
#define ID_BIONICSPIDER_FULLROW         32869
#define ID_ROOT_EXPAND                  32871
#define ID_ROOT_COLLAPSE                32873
#define ID_BIONICSPIDER_GROUP           32874
#define ID_GROUP_ONE                    32876
#define IDD_STATUS                      32877
#define ID_BIONICSPIDER_ANIMATE         32878

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        170
#define _APS_NEXT_COMMAND_VALUE         32879
#define _APS_NEXT_CONTROL_VALUE         1039
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
